### ISSUE TITLE
Add Content button should appear on bottom of area aswell

### ISSUE THREAD

**Issue by buehler** [punkave/apostrophe-editor-2#32]
Hey guys

I'm fiddling around with apostrophe now, and I found a pretty annoying thing:
The "Add content" button is just at the top of an area (let's say a new blog post). While this is not an issue, the problem with inserting new content is that it gets inserted at the top. So while I'm writing a new blogpost, every new image or every new text element that I insert, has to be moved to the bottom.

IMO it would be more useful to the user to either:
Add Content button at the bottom, which inserts the content at the bottom
or
Add content at the bottom by default

I made a screenshot with the demo.apostrophenow.org page :-)

https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/my31q67q.png

Would that be possible?
Cheers
Chris

**Comment by geoffdimasi** [comment]
Good point.

Also, this tip might help: If you hold down shift, the arrows that move
content change in appearance and you can hit them once to send things all
the way to the bottom.

Also, the demo you linked to is for Apostrophe 1.5. The demo for A2 is here:
http://demo.apostrophenow.com/


g.

On Tue, Feb 23, 2016 at 3:47 AM, Christoph Bühler <notifications@github.com>
wrote:

> Hey guys
>
> I'm fiddling around with apostrophe now, and I found a pretty annoying
> thing:
> The "Add content" button is just at the top of an area (let's say a new
> blog post). While this is not an issue, the problem with inserting new
> content is that it gets inserted at the top. So while I'm writing a new
> blogpost, every new image or every new text element that I insert, has to
> be moved to the bottom.
>
> IMO it would be more useful to the user to either:
> Add Content button at the bottom, which inserts the content at the bottom
> or
> Add content at the bottom by default
>
> I made a screenshot with the demo.apostrophenow.org page :-)
>
> https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/my31q67q.png
>
> Would that be possible?
> Cheers
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-editor-2/issues/32>.
>



-- 

Geoff DiMasi, Principal
P'unk Avenue
215 755 1330
punkave.com
@punkave <http://www.twitter.com/punkave>

**Comment by buehler** [comment]
Hey @geoffdimasi 

Thanks, I'll use shift for now :wink: 
For the demo: I meant the new one, sorry I posted the wrong link.

Cheers

**Comment by spacecowboyian** [comment]
Any ideas on where to start making this configurable? I only want the add at the bottom of the content area.

**Comment by boutell** [comment]
This is fixed in A2 0.6, which is currently the "unstable" branch, but will
be in npm soon since we're close to launch on several projects. 0.6 is a
complete rewrite, so code changes are certainly needed but you'll find it's
a dramatic improvement.

On Tue, May 17, 2016 at 5:15 PM, Ian Jennings <notifications@github.com>
wrote:

> Any ideas on where to start making this configurable? I only want the add
> at the bottom of the content area.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-editor-2/issues/32#issuecomment-219856340>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
(This won't be changing in 0.5.)

On Tue, May 17, 2016 at 6:14 PM, Tom Boutell <tom@punkave.com> wrote:

> This is fixed in A2 0.6, which is currently the "unstable" branch, but
> will be in npm soon since we're close to launch on several projects. 0.6 is
> a complete rewrite, so code changes are certainly needed but you'll find
> it's a dramatic improvement.
>
> On Tue, May 17, 2016 at 5:15 PM, Ian Jennings <notifications@github.com>
> wrote:
>
>> Any ideas on where to start making this configurable? I only want the add
>> at the bottom of the content area.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/apostrophe-editor-2/issues/32#issuecomment-219856340>
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
Any hint as to how it will now work? Docs? I don't think it was "broken" really.. just needed an option.

**Comment by boutell** [comment]
Well, you can see yourself if you're brave:

https://github.com/punkave/apostrophe/tree/unstable

(The README is a pretty good guide to getting a site going with 0.6 today.)

On Tue, May 17, 2016 at 9:26 PM, Ian Jennings <notifications@github.com>
wrote:

> Any hint as to how it will now work? Docs? I don't think it was "broken"
> really.. just needed an option.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-editor-2/issues/32#issuecomment-219901069>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
